# This rule is not used by the project production-stack itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to production-stack.vllm.ai resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: production-stack
    app.kubernetes.io/managed-by: kustomize
  name: loraadapter-viewer-role
rules:
- apiGroups:
  - production-stack.vllm.ai
  resources:
  - loraadapters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - production-stack.vllm.ai
  resources:
  - loraadapters/status
  verbs:
  - get
